name: Auto Update RSS Feeds

on:
  schedule:
    # Run every day at midnight UTC
    - cron: '0 0 * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  update-rss:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Update RSS feeds
      run: npm run matrix
      
    - name: Check for changes
      id: check_changes
      run: |
        if git diff --quiet rss.xml weeknotes-rss.xml; then
          echo "has_changes=false" >> $GITHUB_OUTPUT
        else
          echo "has_changes=true" >> $GITHUB_OUTPUT
        fi
        
    - name: Commit and push changes
      if: steps.check_changes.outputs.has_changes == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add rss.xml weeknotes-rss.xml
        git commit -m "Auto-update RSS feeds - $(date +'%Y-%m-%d')"
        git push
        
    - name: No changes found
      if: steps.check_changes.outputs.has_changes == 'false'
      run: echo "No new content to update in RSS feeds" 